version: "3"

volumes:
  mongodata:

services:
  web:
    build: .
    env_file: .env
    ports:
      - "80:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
