version: "3"

volumes:
  mongodata:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app: ticket_webd
    env_file: .env
    ports:
      - "80:8080"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
